services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
  
  fetcher:
    build: ./fetcher
    ports: 
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/content
    depends_on:
      db:
        condition: service_started

  