services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
  
  fetcher:
    build: ./fetcher
    ports: 
      - "3000:3000"
    volumes:
      - ./fetcher:/home/app
      - /home/app/node_modules
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/content
      - BROKER_QUEUE=broker-queue
      - FETCHER_QUEUE=fetcher-queue
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    networks:
      - app-network
  
  broker:
    build: ./crawler-broker
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/content
      - MESSAGE_QUEUE=amqp://rabbitmq
      - BROKER_QUEUE=broker-queue
      - FETCHER_QUEUE=fetcher-queue
    links:
      - rabbitmq
    volumes:
      - ./crawler-broker:/home/app
      - /home/app/node_modules
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - app-network
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  view:
    build: ./crawler-view
    ports:
      - "4200:4200"
    volumes:
      - ./crawler-view:/home/app
      - /home/app/node_modules
    networks:
      - app-network

  api:
    build: ./crawler-api
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./crawler-api/src
    #       target: /home/app/src
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/content
      - MESSAGE_QUEUE=amqp://rabbitmq
      - BROKER_QUEUE=broker-queue
    volumes:
      - ./crawler-api:/home/app
      - /home/app/node_modules
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  db-data:

networks:
  app-network:
    driver: bridge